### ISSUE TITLE
additonal payers to support

### ISSUE THREAD

**Issue by callmenemo491** [makarworld/litewax#5]
Hi, possible for you to include additional payers?
such as:
* NFTHive : **nft.hive - boost**

**Comment by makarworld** [comment]
What sites is have this payers? For add new i should know site and example transaction.

**Comment by callmenemo491** [comment]
NFTHive marketplace (nfthive.io) when buy a drop.
example transaction:
https://wax.bloks.io/transaction/d3471a168c2985dff9efe1cabba66a4a8b6bfc8cd8cf92fc1fd6bb0eb80ee9da?tab=traces

**Comment by makarworld** [comment]
NFTHive does not pay for transactions
To pay in the first action signer it must be NFTHive, but in this example in all actions signer it is nblig.wam
![image](https://github.com/makarworld/litewax/assets/58076271/bed86ad8-71cd-4641-9363-a4a0347110a0)

You can see an example of a transaction that was actually paid: 
neftyblock - https://wax.bloks.io/transaction/b97bef9b990111e8a36bd223760247a6e0f55177881d0c40eb742857aba6bf80
There is an action here that was signed by the neftybrespay account and that is where the transaction was paid from.
![image](https://github.com/makarworld/litewax/assets/58076271/d165a0f6-b9ed-4c05-9c9b-16ba80ab21f0)
